"""empty message

Revision ID: 5e75c2f7d0f8
Revises: f31feb505198
Create Date: 2024-09-19 16:52:44.058938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e75c2f7d0f8'
down_revision: Union[str, None] = 'f31feb505198'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_likes_workout_by_user_id'), 'likes_workout_by_user', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_likes_workout_by_user_id'), table_name='likes_workout_by_user')
    # ### end Alembic commands ###
