"""empty message

Revision ID: e415371658b0
Revises: 5e75c2f7d0f8
Create Date: 2024-09-19 16:54:22.236323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e415371658b0'
down_revision: Union[str, None] = '5e75c2f7d0f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_likes_workout_by_user_id', table_name='likes_workout_by_user')
    op.drop_column('likes_workout_by_user', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('likes_workout_by_user', sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_index('ix_likes_workout_by_user_id', 'likes_workout_by_user', ['id'], unique=False)
    # ### end Alembic commands ###
